=== DHGraz/gamslib/src/gamslib/sip/resources/sip-schema-gams-v1.0.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://gams.uni-graz.at/OAIS/sip-schema-gams-v1.0.json",
    "title": "SIP metadata for GAMS",
    "description": "JSON Schema for GAMS SIPs.",
    "type": "object",
    "properties": {
        "recid": {
            "type": "string",
            "minLength": 4,
            "description": "The record ID of the object. This is typically the identifier of the object in the source repository."
        },
        "title": {
            "type": "string",
            "minLength": 5,
            "description": "The title of the object."
        },
        "project": {
            "type": "string",
            "minLength": 2,
            "description": "The name of the project."
        },
        "description": {
            "type": "string",
            "description": "A description of the object."
        },
        "creator": {
            "type": "string",
            "minLength": 4,
            "description": "The creator of the object."
        },
        "rights": {
            "type": "string",
            "minLength": 3,
            "description": "Rights and licensing information."
        },
        "publisher": {
            "type": "string",
            "minLength": 3,
            "description": "The publisher of the object."
        },
        "source": {
            "type": "string",
            "minLength": 3,
            "description": "A unique string identifying the upstream source digital repository (producer). `local` means the package was created from a local file system."
        },
        "objectType": {
            "type": "string",
            "minLength": 3,
            "description": "The type of the object, e.g. 'text' or 'image'."
        },
        "created_by": {
            "type": "string",
            "description": "The creator of the package (typically a software)."
        },
        "mainResource": {
            "type": "string",
            "description": "The main resource id link of the object."
        },
        "sip_creation_timestamp": {
            "description": "Date time timestamp of SIP creation",
            "type": "number"
        },
        "contentFiles": {
            "type": "array",
            "minItems": 1,
            "description": "An arry of content files",
            "items": {
                "$ref": "#/$defs/contentFile"
            }
        },
        "funder": {
            "type": "string",
            "description": "The funder for the creation of the digital object."
        },
        "lang": {
            "type": "array",
            "description": "A list of languag code associated with the object. Preferred format is either BCP 47 or ISO 639-3."
        },
        "$schema": {
            "type": "string",
            "description": "The schema version of the SIP."
        }
    },
    
    "required": [
            "recid",
            "title",
            "project",
            "creator",
            "rights",
            "contentFiles",
            "publisher",
            "source",
            "objectType",            
            "sip_creation_timestamp",
            "$schema"
        ],
        "additionalProperties": false,
    "$defs": {
        "contentFile": {
            "description": "Object describing a single File with informations from its origin, checksums and bag location",
            "type": "object",
            "properties": {
                "dsid": {
                    "type": "string",
                    "minLength": 3,
                    "description": "The datastream ID of the file."
                },
                "mimetype": {
                    "type": "string",
                    "minLength": 6,
                    "description": "The MIME type of the file."
                },
                "title": {
                    "type": "string",
                    "description": "The title of the file."
                },
                "description": {
                    "type": "string",
                    "description": "A description of the file."
                },
                "creator": {
                    "type": "string",
                    "minLength": 3,
                    "description": "The creator of the file."
                },
                "rights": {
                    "type": "string",
                    "description": "Rights and licensing information."
                },
                "size": {
                    "type": "integer",
                    "description": "The size of the file in bytes."
                },
                "bagpath": {
                    "description": "Path where the file can be found inside the SIP",
                    "type": "string",
                    "minLength": 3
                },
                "lang": {
                    "type": "array",
                    "description": "The language(s) of the file."
                },
                "tags": {
                    "type": "array",
                    "description": "A list of tags associated with the file."
                },
                "puid": {
                    "type": "string",
                    "description": "The pronom PUID of the file."
                },
                "checksums": {
                    "description": "Available checksums for the file. Formatted as '<algorithm> <checksum>', e.g. 'md5 d41d8cd98f00b204e9800998ecf8427e'",
                    "type": "array",
                    "minItems": 1,
                    "items": {
                        "type": "string",
                        "pattern": "^(md5 [a-f0-9]{32}|sha1 [a-f0-9]{40}|sha224 [a-f0-9]{56}|sha256 [a-f0-9]{64}|sha384 [a-f0-9]{96}|sha512 [a-f0-9]{128})$"
                    }
                }
            },
            "required": [
                "bagpath",
                "dsid",
                "mimetype",
                "creator",
                "size",
                "checksums"
            ],
            "additionalProperties": false
        }
    }
}

=== DHGraz/gamslib/tests/sip/validate/data/valid_bag/data/meta/sip.json
{
  "title": "Charles Baissac an Hugo Schuchardt (15-00432)",
  "project": "hsa",
  "description": "digital object description",
  "creator": "Gams HSA Project",
  "rights": "https://creativecommons.org/licenses/by-nc/4.0",
  "publisher": "Institut für Sprachwissenschaft, Karl-Franzens-Universität Graz",
  "contentFiles": [
    {
      "size": 849,
      "bagpath": "data/content/DC.xml",
      "dsid": "dc.xml",
      "mimetype": "text/xml",
      "title": "DC.xml",
      "description": "ds description",
      "creator": "creator 1",
      "rights": "https://creativecommons.org/licenses/by-nc/4.0",
      "lang": ["en"],
      "tags": ["tag1", "tag2"],
      "puid": "fmt/111",
      "checksums": [
          "md5 8f7b2b4b4b4b4b4b4b4b4b4b4b4b4b4b",
          "sha512 e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855c0d16a5daee1436adad79d6c14c1b6a5fb5319723aabd7b7a7ef51ad7f8fa6e7"
     ]
    },
    {
      "size": 76255,
      "bagpath": "data/content/IMG.jpeg",
      "dsid": "IMG.jpeg",
      "mimetype": "text/xml",
      "title": "img1.jpeg",
      "description": "img description",
      "creator": "creator 1",
      "rights": "https://creativecommons.org/licenses/by-nc/4.0",
      "lang": ["en"],
      "tags": ["tag1", "tag2"],
      "puid": "fmt/111",
      "checksums": [
        "md5 8f7b2b4b4b4b4b4b4b4b4b4b4b4b4b4b",
        "sha512 e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855c0d16a5daee1436adad79d6c14c1b6a5fb5319723aabd7b7a7ef51ad7f8fa6e7"
      ]
    }
  ],
  "$schema":  "https://gams.uni-graz.at/pub/gams/static/schemas/sip-schema-gams-v1.0.json",
  "created_by": "CSV to SIP JSON converter",
  "sip_creation_timestamp": 1777282176.7894132,
  "source": "local",
  "recid": "hsa.letter.1",
  "objectType": "text",
  "mainResource": "IMG.jpeg",
  "lang": ["fr", "de"],
  "funder": "The project funder"
}

=== DHGraz/gamslib/tests/sip/test_schema/sip.json
{
  "$schema": "https://gams.uni-graz.at/OAIS/sip-schema-gams-v1.0.json",
  "title": "Charles Baissac an Hugo Schuchardt (15-00432)",
  "project": "hsa",
  "description": "digital object description",
  "creator": "Gams HSA Project",
  "rights": "https://creativecommons.org/licenses/by-nc/4.0",
  "publisher": "Institut für Sprachwissenschaft, Karl-Franzens-Universität Graz",
  "contentFiles": [
    {
      "size": 849,
      "bagpath": "data/content/DC.xml",
      "dsid": "dc.xml",
      "mimetype": "text/xml",
      "title": "DC.xml",
      "description": "ds description",
      "creator": "creator 1",
      "rights": "https://creativecommons.org/licenses/by-nc/4.0",
      "lang": ["en"],
      "tags": ["tag1", "tag2"],
      "puid": "fmt/111",
      "checksums": [
            "md5 8f7b2b4b4b4b4b4b4b4b4b4b4b4b4b4b",
            "sha512 e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855c0d16a5daee1436adad79d6c14c1b6a5fb5319723aabd7b7a7ef51ad7f8fa6e7"
      ]
    },
    {
      "size": 76255,
      "bagpath": "data/content/IMG.jpeg",
      "dsid": "p1.dc.xml",
      "mimetype": "text/xml",
      "title": "img1.jpeg",
      "description": "img description",
      "creator": "creator 1",
      "rights": "https://creativecommons.org/licenses/by-nc/4.0",
      "lang": ["en"],
      "tags": ["tag1", "tag2"],
      "puid": "fmt/111",
      "checksums": [
          "md5 8f7b2b4b4b4b4b4b4b4b4b4b4b4b4b4b",
          "sha512 e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855c0d16a5daee1436adad79d6c14c1b6a5fb5319723aabd7b7a7ef51ad7f8fa6e7"
      ]
    }
  ],

  "created_by": "CSV to SIP JSON converter",
  "source": "local",
  "recid": "hsa.letter.1",
  "objectType": "text",
  "mainResource": "IMG.jpeg",
  "lang": ["fr", "de"],
  "funder": "The project funder",
  "sip_creation_timestamp": 1777282176.7894132
}
